export type ModuleKey = "video" | "sales" | "recall" | "brain";
export type ScreenCadence = "setup" | "daily";

export type Screen = {
  id: string;
  module: ModuleKey;
  index: string;
  title: string;
  phase: string;
  cadence?: ScreenCadence;
  summary: string;
  output: string;
  duration: string;
  instructions: string[];
  done: string[];
  detail?: boolean;
  parent?: string;
};

export const moduleMeta: Record<
  ModuleKey,
  { index: string; label: string; caption: string }
> = {
  video: { index: "01", label: "短视频获客", caption: "做今天的视频" },
  sales: { index: "02", label: "企微自动接待", caption: "看今天的接待" },
  recall: { index: "03", label: "沉默客户跟进", caption: "处理今天的跟进" },
  brain: { index: "04", label: "企业大脑", caption: "维护企业知识" },
};

export const mainScreens: Screen[] = [
  {
    id: "video-business",
    module: "video",
    index: "01",
    title: "先选门店做什么生意",
    phase: "引导流程",
    cadence: "setup",
    summary: "告诉系统门店真正能做哪些品类、能服务哪些城市。以后推荐的视频和客户内容都会按这里筛选。",
    output: "门店业务范围",
    duration: "3 分钟",
    instructions: [
      "先点选门店真正能做的品类，可以多选",
      "再点选能够上门服务的城市",
      "检查已选数量，点“保存并匹配视频”",
      "看到绿色“已保存”后，再继续下一步",
    ],
    done: ["主营品类不是空白", "服务城市不是空白", "页面显示“已保存”"],
  },
  {
    id: "video-label",
    module: "video",
    index: "02",
    title: "告诉系统哪些视频适合本店",
    phase: "引导流程",
    cadence: "setup",
    summary: "看完 10 条示例视频，判断“本店适合拍”还是“不适合”。系统会照着你的选择继续找素材。",
    output: "本店的视频偏好",
    duration: "8 分钟",
    instructions: [
      "先点封面看完整视频，不要只看标题",
      "与本店业务相关、门店也能拍，就点“适合本店”",
      "业务无关或门店做不了，就点“不适合本店”",
      "进度达到 10/10 后再继续；点错可以撤销",
    ],
    done: ["进度显示 10/10", "每条视频都有选择", "系统给出本店偏好总结"],
  },
  {
    id: "video-slices",
    module: "video",
    index: "03",
    title: "上传门店真实视频",
    phase: "引导流程",
    cadence: "setup",
    summary: "把完工、安装和展厅实拍上传进来。系统会自动拆成可重复使用的小片段，并写出每段拍了什么。",
    output: "可复用的门店视频片段",
    duration: "5–15 分钟",
    instructions: [
      "点“上传门店视频”，选择手机或电脑里的实拍",
      "状态显示“分析中”时先等待，不用反复上传",
      "分析完成后，点“检查片段”查看每段内容",
      "改正不准确的说明，再保存进素材库",
    ],
    done: ["上传的视频显示“分析完成”", "每个片段说明都符合实际画面", "有用片段已保存进素材库"],
  },
  {
    id: "video-spokesperson",
    module: "video",
    index: "04",
    title: "准备店长出镜素材",
    phase: "引导流程",
    cadence: "setup",
    summary: "按示范拍 1 张正面照和 3 段短视频。系统以后才能用同一个店长形象制作口播。",
    output: "可用于制作视频的店长素材",
    duration: "15 分钟",
    instructions: [
      "确认出镜人姓名、门店和本人授权",
      "上传清晰正面照：平视、无遮挡、光线均匀",
      "按页面要求分别拍“正面口播、转身展示、四种语气”",
      "逐项看示例，收音或画面不合格就重拍",
    ],
    done: ["正面照片检查通过", "3 种视频都显示“可使用”", "出镜人授权已确认"],
  },
  {
    id: "video-top",
    module: "video",
    index: "05",
    title: "选今天要参考的视频",
    phase: "每日任务",
    cadence: "daily",
    summary: "从最近 3 天表现较好的同行视频里选 1 条，只参考它的讲法和节奏，不照搬内容。",
    output: "今天的参考视频",
    duration: "10 分钟",
    instructions: [
      "先看今天；候选视频不合适再看昨天或前天",
      "至少完整看 3 条，并点“看详情”了解数据",
      "优先选本店做得了、客户也关心的主题",
      "点“选这条”，再点“用它做今天的参考”",
    ],
    done: ["至少看过 3 条完整视频", "知道选中视频好在哪里", "页面显示“已选为今天参考”"],
  },
  {
    id: "video-report",
    module: "video",
    index: "06",
    title: "看懂参考视频为什么有效",
    phase: "每日任务",
    cadence: "daily",
    summary: "系统会把视频分成“开头吸引人—说明问题—展示方案—给出证据—邀请行动”几段，告诉你哪些做法可以借鉴。",
    output: "可借鉴的视频拍法",
    duration: "2–5 分钟",
    instructions: [
      "先等系统分析完成",
      "先读“为什么有效”，再逐段看画面和话术",
      "确认哪些做法本店能拍、哪些不能照搬",
      "没有问题后，点“按这个结构制作”",
    ],
    done: ["分析状态显示“完成”", "已看懂 5 个片段各自作用", "已确认不照搬别家户型、文案和价格"],
  },
  {
    id: "video-progress",
    module: "video",
    index: "07",
    title: "等系统制作今天的视频",
    phase: "每日任务",
    cadence: "daily",
    summary: "这里会显示脚本、画面、口播、剪辑和检查分别做到哪一步。出现红色失败时，再按提示处理。",
    output: "今天的视频制作进度",
    duration: "3–8 分钟",
    instructions: [
      "先看总进度和预计剩余时间",
      "绿色是已完成，黄色是正在做，红色才需要处理",
      "有红色失败时，点“查看问题”看店长要补什么",
      "制作未到 100% 前不要去下载成片",
    ],
    done: ["总进度达到 100%", "没有红色“需要处理”", "页面提示“成片可以检查”"],
  },
  {
    id: "video-result",
    module: "video",
    index: "08",
    title: "检查并下载今天的成片",
    phase: "每日任务",
    cadence: "daily",
    summary: "从头播放一遍，重点核对字幕、口播、门店名称、价格和画面。确认无误后再下载发布。",
    output: "可以发布的视频文件",
    duration: "5 分钟",
    instructions: [
      "从头到尾播放推荐版本，不能只看自动检查",
      "逐项看字幕、声音、门店角标、价格和音乐版权",
      "有黄色或红色提示时，先修改或重新生成",
      "全部确认后，点“下载可发布视频”",
    ],
    done: ["人工从头看完一遍", "8 项自动检查全部通过", "下载的是标有“推荐版”的文件"],
  },

  {
    id: "sales-training",
    module: "sales",
    index: "01",
    title: "上传机器人回答客户时可用的门店资料",
    phase: "引导流程",
    cadence: "setup",
    summary: "上传门店确认过的价格、活动、服务区域和售后资料。机器人只使用标为“可用”的内容；不确定时会交给真人销售。",
    output: "机器人回答客户时可用的门店资料",
    duration: "10 分钟",
    instructions: [
      "先上传最新价格表、活动规则、服务区域和售后说明",
      "等状态显示“已读懂”，再点开检查重点内容",
      "看到“说法不一致”时，选择哪一份资料为准",
      "待处理数量变成 0 后再继续",
    ],
    done: ["价格、活动、服务区域、售后四类资料齐全", "所有资料都标明有效期和负责人", "待处理的说法不一致为 0"],
  },
  {
    id: "sales-champion",
    module: "sales",
    index: "02",
    title: "上传并检查 10 段销售聊天",
    phase: "引导流程",
    cadence: "setup",
    summary: "放入沟通效果好的聊天，确认隐私和客户结果，再把不得体的销售回复标为“不建议借鉴”。",
    output: "逐句核对过的销售沟通示例",
    duration: "15 分钟",
    instructions: [
      "点“放入企微聊天”，选择店里沟通效果好的记录",
      "检查姓名、电话和详细地址是否已自动遮住",
      "确认实际结果：到店、量房、继续沟通或未成交",
      "销售回复默认可借鉴；不妥的句子改为“不建议借鉴”",
    ],
    done: ["已选满 10 段聊天", "客户隐私已遮住", "每句销售回复都已确认"],
  },
  {
    id: "sales-simulation",
    module: "sales",
    index: "03",
    title: "像带新人一样给机器人回答打分",
    phase: "引导流程",
    cadence: "setup",
    summary: "看客户问题和机器人回答，分别判断它有没有听懂、有没有答对、有没有乱承诺、有没有自然推进下一步。",
    output: "100 组回答判断",
    duration: "30–60 分钟",
    instructions: [
      "先读客户问题，再读机器人准备发送的回答",
      "四项分别打分：1 分有明显问题，3 分基本可用，5 分可直接发送",
      "任一项低于 3 分时，在下方写出正确说法",
      "可随时保存稍后继续，不需要一次做完 100 组",
    ],
    done: ["进度显示 100/100", "四项都分别评分", "所有低分回答都写了正确版本"],
  },
  {
    id: "sales-prompt",
    module: "sales",
    index: "04",
    title: "确认机器人怎么说、哪些话不能说",
    phase: "引导流程",
    cadence: "setup",
    summary: "用门店语言确认说话口吻、必须问清的信息、可以承诺的内容，以及哪些情况必须交给真人销售。",
    output: "机器人说话规则",
    duration: "10 分钟",
    instructions: [
      "直接在输入框修改说话口吻、要先问什么、哪些话不能承诺",
      "价格、活动名额和服务范围必须来自已确认资料",
      "投诉、明确拒绝或复杂施工问题要交给真人销售",
      "修改完成后点“提交并应用”",
    ],
    done: ["页面显示“当前规则已应用”", "不会乱报价格和活动名额", "交给真人销售的条件清楚"],
  },
  {
    id: "sales-metrics",
    module: "sales",
    index: "05",
    title: "看今天企微接待效果",
    phase: "每日运营",
    cadence: "daily",
    summary: "按“新增企微—有效对话—明确需求—预约到店—实际到店”看今天效果，并进入下一步检查可能答错的聊天。",
    output: "今天的接待结果和待检查聊天入口",
    duration: "5 分钟",
    instructions: [
      "先确认企业微信显示“正在接待”；看到二维码时先让门店员工扫码登录",
      "先确认日期和数据更新时间",
      "从左到右看客户人数在哪一步掉得最多",
      "看页面给出的异常提醒和简单原因",
      "点“检查聊天”，进入下一步处理可能答错的回复",
    ],
    done: ["企业微信已连接，云电脑显示“正在接待”", "日期和数据更新时间正确", "知道今天掉得最多的一步", "已进入下一步处理可能答错的聊天"],
  },
  {
    id: "sales-quality",
    module: "sales",
    index: "06",
    title: "检查机器人与客户的聊天示例",
    phase: "每日运营",
    cadence: "daily",
    summary: "优先看“机器人回复可能有错误”和“到店意向高”的聊天，判断是否合格；有问题就修改或交给真人销售。",
    output: "聊天检查结果和真人跟进任务",
    duration: "15 分钟",
    instructions: [
      "先看标为“机器人回复可能有错误”的聊天",
      "逐轮核对客户需求、回答依据和是否乱承诺",
      "没问题点“合格，下一条”；有问题点“标记并修改”",
      "需要员工继续谈时，点“交给真人销售”并选择负责人",
    ],
    done: ["所有“回复可能有错误”的聊天都已处理", "有问题的回复写明原因", "交给真人的任务有负责人和截止时间"],
  },
  {
    id: "sales-faq",
    module: "sales",
    index: "07",
    title: "修改客户常问问题的答案",
    phase: "每日运营",
    cadence: "daily",
    summary: "先改“客户问得多、满意度又低”的问题。答案中的价格、活动和服务范围必须来自最新门店资料。",
    output: "可直接用于客户回复的标准答案",
    duration: "15 分钟",
    instructions: [
      "按“最值得先处理”查看列表",
      "打开第一条待处理问题，先看客户实际问法",
      "修改答案并选择它依据哪份门店资料",
      "用 3 种相似问法试一遍，再应用新答案",
    ],
    done: ["列表中没有“待处理”问题", "新答案通过 3 种问法测试", "每个答案都能看到资料来源"],
  },
  {
    id: "sales-plugins",
    module: "sales",
    index: "08",
    title: "设置机器人可以自动办理的服务",
    phase: "自动能力",
    cadence: "setup",
    summary: "在同一页选择服务、查看客户会收到什么、配置门店资料并试运行。4 个示例都正确后，再启用这项服务。",
    output: "经过试运行的自动接待服务",
    duration: "12 分钟",
    instructions: [
      "选择一项自动接待服务，并查看客户会收到的内容",
      "在本页补全启动条件、门店、服务区域和资料来源",
      "修改会自动保存为草稿；再用 4 个正反示例试运行",
      "全部通过后点“确认结果后启用”",
    ],
    done: ["4 个正反示例结果正确", "使用的门店资料仍在有效期", "服务状态明确显示“使用中”或“草稿”"],
  },

  {
    id: "recall-activities",
    module: "recall",
    index: "01",
    title: "准备可用于客户跟进的活动",
    phase: "资料设置",
    cadence: "setup",
    summary: "系统只能使用这里已经确认、仍在有效期内而且还有名额的活动。请核对时间、权益、每天可接待人数和客户会看到的海报。",
    output: "可用于客户消息的活动",
    duration: "10 分钟",
    instructions: [
      "填写活动名称、开始和结束日期",
      "核对客户能获得什么，以及每天可接待多少人",
      "上传海报并预览客户看到的内容",
      "先保存草稿，再点“保存并设为可使用”",
    ],
    done: ["活动仍在有效期", "价格、权益和可预约人数有资料依据", "页面显示“可使用”"],
  },
  {
    id: "recall-metrics",
    module: "recall",
    index: "02",
    title: "看哪些跟进方式更有效",
    phase: "每日运营",
    cadence: "daily",
    summary: "先看客户回复率，再看预约量房和实际到店人数。页面会按每次联系和内容类型告诉你什么值得继续、什么应该减少。",
    output: "跟进效果结论",
    duration: "6 分钟",
    instructions: [
      "选择要看的时间范围",
      "先看回复率、预约量房和实际到店人数",
      "比较第 1 到第 7 次联系后的客户回复率",
      "看到“减少使用”时记下内容名称，再到下一步查看正在跟进的客户",
    ],
    done: ["统计时间范围正确", "知道回复率最高的联系次数和内容", "知道哪类内容应减少使用"],
  },
  {
    id: "recall-pool",
    module: "recall",
    index: "03",
    title: "找出今天最值得跟进的客户",
    phase: "每日运营",
    cadence: "daily",
    summary: "打开一位客户，就能同时查看以前聊了什么，并安排接下来要发的案例、知识或权益内容。客户已拒绝、已选别家或已成交时，系统立即停止。",
    output: "客户历史和后续跟进安排",
    duration: "15 分钟",
    instructions: [
      "按“联系时间最近”或“跟进优先分最高”排序",
      "在本演示中可按客户姓名搜索；真实系统也可用手机号后 4 位",
      "打开客户，同时查看历史沟通和后续消息安排",
      "逐条修改要发送的内容；客户明确拒绝时停止自动联系",
    ],
    done: ["今天到期客户都已查看", "历史沟通和后续消息在同一页", "已停止客户不会再自动发送"],
  },
  {
    id: "recall-plugins",
    module: "recall",
    index: "05",
    title: "选择自动生成的跟进内容",
    phase: "自动能力",
    cadence: "setup",
    summary: "选择知识海报或量房券，进入相应设置；保存后回到这里查看使用状态。",
    output: "可使用的自动跟进工具",
    duration: "5 分钟",
    instructions: [
      "先看工具适合什么客户、近 30 天效果如何",
      "选择“设置知识海报”或“设置量房券”",
      "在设置页确认什么情况下生成、会使用哪些资料",
      "保存后回到本页查看工具状态",
    ],
    done: ["启用的工具写明适用客户", "数据来源和最后更新时间清楚", "两项工具都能打开并保存设置"],
  },
  {
    id: "recall-poster",
    module: "recall",
    index: "06",
    title: "制作按客户情况生成的知识海报",
    parent: "recall-plugins",
    phase: "自动能力",
    cadence: "setup",
    summary: "选择客户情况和知识主题，预览客户将看到的海报后保存。",
    output: "知识海报生成规则",
    duration: "8 分钟",
    instructions: [
      "选择客户目前处于哪个装修或沟通阶段",
      "选择预算、板材、收纳或装修流程主题",
      "用示例客户预览；缺少面积或风格时不能让系统猜",
      "核对品牌落款和提示语，保存生成规则",
    ],
    done: ["海报内容适合所选客户阶段", "示例数据明确标为“仅预览”", "规则已保存"],
  },
  {
    id: "recall-coupon",
    module: "recall",
    index: "07",
    title: "制作免费上门量房券",
    parent: "recall-plugins",
    phase: "自动能力",
    cadence: "setup",
    summary: "只有客户地址在服务范围内，而且所选日期还有可预约名额，系统才会生成每位客户专属的量房券。",
    output: "可核对预约名额的量房券模板",
    duration: "8 分钟",
    instructions: [
      "选择门店实际能够上门的区域",
      "设置客户领取后多久必须预约",
      "连接门店预约表，确认每天可预约数量",
      "预览唯一券码和使用说明，再保存",
    ],
    done: ["服务区域与门店能力一致", "有效期和每户使用次数清楚", "发送前会再次检查可预约名额"],
  },

  {
    id: "brain-inbox",
    module: "brain",
    index: "01",
    title: "资料收集箱",
    phase: "资料设置",
    cadence: "setup",
    summary: "任意上传企业文档，系统自动识别知识模块，同时保存原始文件版本、页码、章节、段落或单元格定位。",
    output: "已进入处理队列的企业资料",
    duration: "3 分钟",
    instructions: ["上传 PDF、Word、Excel、PPT 或扫描件", "查看系统识别出的模块和处理状态", "发现重复或过期资料时及时删除", "继续补充合同、售后和验收资料"],
    done: ["原始文件已不可变保存", "每条事实绑定人类可读的原文位置", "建议补充的资料已经明确"],
  },
  {
    id: "brain-processing",
    module: "brain",
    index: "02",
    title: "文档处理详情",
    phase: "资料设置",
    cadence: "setup",
    summary: "查看文件解析、原文分块、事实抽取、证据绑定、冲突比较和草稿生成的完整过程。",
    output: "可追溯的结构化企业事实",
    duration: "2–5 分钟",
    instructions: ["先看当前处理进度", "检查抽取出的价格、付款和服务范围", "点开原文件位置核对证据", "有冲突的内容进入待决策中心"],
    done: ["原件和版本已保存", "事实可定位到页码、章节或单元格", "缺出处内容保持草稿"],
  },
  {
    id: "brain-overview",
    module: "brain",
    index: "03",
    title: "企业大脑全景",
    phase: "每日运营",
    cadence: "daily",
    summary: "按企业核心、行业通用和企业独有查看生产资料形成的知识模块；行业条目实时读取，敏感资料保持隔离。",
    output: "企业知识目录和处理入口",
    duration: "5 分钟",
    instructions: ["先看资料、模块和待确认数量", "按三大分类扫描知识覆盖情况", "优先处理待确认和缺资料模块", "新业务主题在动态扩展区查看"],
    done: ["真实模块分类清楚", "3 项承诺冲突有处理计划", "行业库连接状态可见"],
  },
  {
    id: "brain-core",
    module: "brain",
    index: "04",
    title: "企业核心模块",
    phase: "资料设置",
    cadence: "setup",
    summary: "维护来自生产档案的企业定位、产品、价格、材料、服务区域、活动和承诺边界。",
    output: "可验证的企业核心事实",
    duration: "8 分钟",
    instructions: ["从左侧选择一个核心模块", "查看当前生效事实和适用范围", "检查原始文件名、段落位置和原文摘录", "缺失或冲突内容进入对应处理入口"],
    done: ["产品和服务边界明确", "价格与活动均有有效期", "每条事实能回到用户原始文档"],
  },
  {
    id: "brain-industry",
    module: "brain",
    index: "05",
    title: "行业通用模块",
    phase: "资料设置",
    cadence: "setup",
    summary: "从生产知识库实时整理装修流程、预算、材料、工艺、安装验收和售后等行业通用知识。",
    output: "装修行业通用知识底库",
    duration: "8 分钟",
    instructions: ["按标准工序查看行业知识", "区分行业标准和企业覆盖值", "核对原始文件与段落定位", "企业实际做法不同的地方进入企业独有模块"],
    done: ["行业模块来自真实分类", "行业标准和企业标准分开", "条目可回到原文件位置"],
  },
  {
    id: "brain-unique",
    module: "brain",
    index: "06",
    title: "企业独有模块",
    phase: "资料设置",
    cadence: "setup",
    summary: "记录有大有小实际执行的十步订单 SOP、付款节点、生产安装、售后、增项和服务覆盖边界。",
    output: "企业真实履约标准",
    duration: "10 分钟",
    instructions: ["选择一个企业独有模块", "查看负责人、时效、输入输出和异常处理", "核对原始文件、章节与原文摘录", "需要人工完成的能力明确标记"],
    done: ["执行流程和负责人明确", "服务能力边界诚实", "例外和人工兜底可以查到"],
  },
  {
    id: "brain-decisions",
    module: "brain",
    index: "07",
    title: "待决策中心",
    phase: "每日运营",
    cadence: "daily",
    summary: "只展示生产资料中真正冲突、且会影响退款、加急、售后时效或服务表达的内容。",
    output: "需要企业负责人确认的选择题",
    duration: "5–15 分钟",
    instructions: ["先处理高风险的价格和付款冲突", "查看 AI 推荐和推荐理由", "低风险项目可以批量接受", "承诺类内容必须逐项确认"],
    done: ["3 项承诺冲突都有结论", "选择结果保留原来源", "发布草稿已经更新"],
  },
  {
    id: "brain-conflict",
    module: "brain",
    index: "08",
    title: "冲突选择题",
    phase: "每日运营",
    cadence: "daily",
    summary: "对比来自原始文件具体段落的候选口径；出处不完整时只能采用临时安全方案并转人工核对。",
    output: "一条正式生效的企业事实",
    duration: "3 分钟",
    instructions: ["先读清问题影响范围", "逐项查看来源和有效期", "选择原版本或 AI 融合方案", "确认写入后返回下一题"],
    done: ["选择绑定原始文件和段落", "历史版本继续保留", "出处不完整时禁止发布"],
  },
  {
    id: "brain-expansion",
    module: "brain",
    index: "09",
    title: "AI 扩展模块",
    phase: "资料设置",
    cadence: "setup",
    summary: "上传资料出现现有目录无法覆盖的独立业务主题时，AI 只根据真实来源建议新模块结构，不补写承诺。",
    output: "经过确认的新知识模块",
    duration: "5 分钟",
    instructions: ["查看为什么不能归入现有模块", "检查 AI 抽取的模块字段", "资料不足时保留为候选", "确认后进入发布草稿"],
    done: ["新模块不与现有目录重复", "字段和来源完整", "候选主题没有被强行发布"],
  },
  {
    id: "brain-release",
    module: "brain",
    index: "10",
    title: "版本与发布",
    phase: "每日运营",
    cadence: "daily",
    summary: "真实生产快照必须通过原始文件、段落定位、隐私、内容边界与承诺冲突检查后再发布。",
    output: "可回滚的企业大脑版本",
    duration: "5 分钟",
    instructions: ["对比线上版本和草稿版本", "检查新增、更新和归档内容", "确认六项发布检查通过", "发布后保留完整回滚记录"],
    done: ["质量检查全部通过", "变更范围清楚", "新版本可以安全回滚"],
  },
];

export const detailScreens: Screen[] = [
  {
    id: "video-label-detail", module: "video", index: "D01", title: "检查一条视频判断",
    parent: "video-label", phase: "详情页",
    summary: "完整播放这条视频，确认它是否适合本店客户，并告诉系统具体原因。",
    output: "这一条视频的判断", duration: "2 分钟",
    instructions: ["从头播放视频", "选择“适合本店”或“不适合本店”", "勾选具体原因", "保存后返回下一条"],
    done: ["视频已完整播放", "判断和原因都已选择", "页面显示保存成功"], detail: true,
  },
  {
    id: "video-slice-detail", module: "video", index: "D02", title: "检查拆出的门店视频片段",
    parent: "video-slices", phase: "详情页",
    summary: "逐段播放系统拆出的小片段，决定保留还是不用，并改正不准确的画面说明。",
    output: "确认可用的门店素材", duration: "5 分钟",
    instructions: ["先看原始视频", "逐段播放自动拆出的片段", "选择“保留”或“不使用”", "改正说明并保存"],
    done: ["所有片段都已播放", "每段都有保留决定", "画面说明符合实际"], detail: true,
  },
  {
    id: "video-spokesperson-detail", module: "video", index: "D03", title: "检查店长拍摄素材和授权",
    parent: "video-spokesperson", phase: "详情页",
    summary: "检查正面照、3 段视频、声音和本人授权；不合格的项目会给出明确重拍方法。",
    output: "可使用的店长拍摄素材", duration: "5 分钟",
    instructions: ["检查照片清晰度和入镜范围", "分别播放 3 段视频", "按提示重拍不合格内容", "确认授权期限和用途"],
    done: ["照片和 3 段视频都可使用", "声音和光线检查通过", "授权状态与期限清楚"], detail: true,
  },
  {
    id: "video-competitor-detail", module: "video", index: "D04", title: "看同行视频为何值得参考",
    parent: "video-top", phase: "详情页",
    summary: "完整播放所选同行视频，查看排名依据和客户评论问题，只借鉴结构，不复制对方内容。",
    output: "是否选为今天参考", duration: "3 分钟",
    instructions: ["完整播放视频", "查看未投广告播放、看完比例和收藏数据", "阅读客户最常问的问题", "确认或取消参考"],
    done: ["视频已完整播放", "知道它适合本店的原因", "已作出是否参考的决定"], detail: true,
  },
  {
    id: "video-log-detail", module: "video", index: "D05", title: "查看制作问题和处理办法",
    parent: "video-progress", phase: "详情页",
    summary: "把技术记录翻成店长能处理的事项：哪些已经自动解决，哪些必须补资料。",
    output: "待处理问题清单", duration: "2 分钟",
    instructions: ["先看红色“需要你处理”", "忽略已自动解决的记录", "按唯一处理按钮补资料", "确认制作重新开始"],
    done: ["没有未读的红色问题", "需补资料的步骤已处理", "制作状态重新变为进行中"], detail: true,
  },
  {
    id: "video-result-detail", module: "video", index: "D06", title: "核对成片版本和检查证据",
    parent: "video-result", phase: "详情页",
    summary: "对比推荐版、大字幕版和初稿，查看每项检查对应的视频时间点和下载记录。",
    output: "最终确认的成片版本", duration: "5 分钟",
    instructions: ["播放推荐版和需要对比的版本", "查看每项检查的证据时间点", "人工核对产品、价格和门店信息", "确认版本后下载"],
    done: ["推荐版已完整播放", "自动检查和人工检查都完成", "下载记录显示正确版本"], detail: true,
  },
  {
    id: "sales-training-detail", module: "sales", index: "D07", title: "核对一份门店资料",
    parent: "sales-training", phase: "详情页",
    summary: "对照原文件检查系统读出的价格、包含项、有效期和负责人；有两种说法时选择哪份为准。",
    output: "可供机器人使用的资料", duration: "5 分钟",
    instructions: ["核对文件名、版本和有效期", "逐条对照原文件位置", "处理说法不一致", "确认负责人后保存"],
    done: ["重点内容与原文件一致", "说法不一致为 0", "有效期和负责人已填写"], detail: true,
  },
  {
    id: "sales-champion-detail", module: "sales", index: "D08", title: "逐句确认这段销售聊天",
    parent: "sales-champion", phase: "详情页",
    summary: "客户原话只作背景；逐句决定哪些销售回复可以借鉴。",
    output: "逐句核对过的销售回复", duration: "4 分钟",
    instructions: ["检查客户隐私已遮住", "阅读完整聊天和实际结果", "把不妥的销售回复改为“不建议借鉴”", "确认后保存"],
    done: ["隐私检查通过", "每句销售回复都已确认", "实际客户结果已确认"], detail: true,
  },
  {
    id: "sales-simulation-detail", module: "sales", index: "D09", title: "查看评分理由并改写回答",
    parent: "sales-simulation", phase: "详情页",
    summary: "查看四项独立评分；有低分时，把你希望机器人对客户说的话写出来。",
    output: "这道练习的正确回答", duration: "3 分钟",
    instructions: ["查看客户问题和原回答", "分别检查四项分数", "阅读低分原因", "写出正确版本并保存"],
    done: ["四项都有独立分数", "低分原因清楚", "正确回答已保存"], detail: true,
  },
  {
    id: "sales-conversation-detail", module: "sales", index: "D10", title: "检查一段客户聊天示例",
    parent: "sales-quality", phase: "详情页",
    summary: "逐轮看客户当时想要什么、机器人使用了哪份资料、回复是否合适，以及何时应该交给真人。",
    output: "聊天处理结论", duration: "5 分钟",
    instructions: ["阅读完整聊天", "核对每轮客户需求和回答依据", "选择合格、修改或交给真人", "填写原因和负责人"],
    done: ["每个风险点都有结论", "需要修改的回复写明原因", "真人跟进任务已分配"], detail: true,
  },
  {
    id: "sales-faq-detail", module: "sales", index: "D11", title: "修改一条客户常问答案",
    parent: "sales-faq", phase: "详情页",
    summary: "编辑客户看到的标准回答，选择它依据哪份门店资料，并用 3 种相似问法试一遍。",
    output: "测试通过的新答案", duration: "5 分钟",
    instructions: ["查看客户最近的常见问法", "修改标准回答", "选择资料来源和适用范围", "用 3 种问法测试后应用"],
    done: ["回答没有超出门店资料", "3 种问法测试通过", "新答案状态显示已应用"], detail: true,
  },
  {
    id: "recall-activity-detail", module: "recall", index: "D12", title: "确认一个活动现在还能不能用",
    parent: "recall-activities", phase: "详情页",
    summary: "核对活动周期、客户权益、每天可预约人数、海报和已经发送或使用的记录。",
    output: "活动可用状态", duration: "4 分钟",
    instructions: ["检查开始和结束日期", "核对权益、价格和可预约人数", "预览客户海报", "选择继续使用、暂停或结束"],
    done: ["活动时间和权益仍有效", "可预约人数有最新来源", "活动状态已保存"], detail: true,
  },
  {
    id: "recall-customer-detail", module: "recall", index: "D13", title: "查看客户并安排后续内容",
    parent: "recall-pool", phase: "详情页",
    summary: "在同一页查看这位客户以前怎么聊、目前处于什么阶段，并安排接下来最多 7 次的案例、知识或权益内容。",
    output: "客户历史和后续消息计划", duration: "10 分钟",
    instructions: ["查看历史沟通和客户当前阶段", "逐条检查准备发送的内容和时间", "需要时修改单条内容", "客户明确拒绝时停止自动联系"],
    done: ["历史沟通与后续计划在同一页", "每条内容和时间清楚", "拒绝客户不会再自动联系"], detail: true,
  },
  {
    id: "recall-cadence-detail", module: "recall", index: "D14", title: "编辑一条客户跟进消息",
    parent: "recall-customer-detail", phase: "详情页",
    summary: "从客户详情进入，只修改这一条消息的内容、附件、发送时间和原因；保存后直接回到这位客户的计划。",
    output: "已保存的单条跟进消息", duration: "5 分钟",
    instructions: ["确认客户和第几次联系", "修改消息、附件和发送时间", "核对为什么现在发送", "保存并放回客户计划"],
    done: ["客户和发送时间正确", "消息与客户当前阶段匹配", "修改已保存到客户计划"], detail: true,
  },
];

export const allScreens = [...mainScreens, ...detailScreens];

export const videos = [
  { title: "33㎡钻石厨房：台面多出 1.8 米", account: "漳州住小帮", duration: "00:42", views: "8.6万", likes: "6,842", comments: "312", saves: "1,486", shares: "729" },
  { title: "118㎡原木风全屋定制完工实拍", account: "有大有小全屋定制", duration: "00:36", views: "7.9万", likes: "5,901", comments: "286", saves: "1,224", shares: "614" },
  { title: "568 元/㎡套餐到底包含什么", account: "漳州定制阿杜", duration: "00:51", views: "6.8万", likes: "5,421", comments: "438", saves: "1,063", shares: "508" },
  { title: "8㎡儿童房收纳翻倍方案", account: "小户型改造局", duration: "00:29", views: "6.4万", likes: "4,872", comments: "197", saves: "1,522", shares: "469" },
  { title: "ENF 板材怎么选：三个误区", account: "板材研究社", duration: "00:47", views: "5.9万", likes: "4,215", comments: "369", saves: "1,305", shares: "392" },
  { title: "安装现场：柜门缝隙做到 2mm", account: "安装师傅老陈", duration: "00:33", views: "5.4万", likes: "3,986", comments: "241", saves: "892", shares: "361" },
  { title: "奶油风翻车的 5 个细节", account: "设计师周周", duration: "00:55", views: "4.9万", likes: "3,744", comments: "412", saves: "1,109", shares: "347" },
  { title: "旧房翻新先做柜体还是水电", account: "闽南旧改", duration: "00:40", views: "4.6万", likes: "3,205", comments: "334", saves: "948", shares: "298" },
  { title: "同户型改造前后动线对比", account: "空间答案", duration: "00:31", views: "4.2万", likes: "3,012", comments: "173", saves: "862", shares: "281" },
  { title: "店长带看：漳州龙文展厅", account: "有大有小门店", duration: "00:38", views: "3.8万", likes: "2,841", comments: "216", saves: "731", shares: "253" },
];

export const customers = [
  ["林女士", "设计方案比较中", "已报价未到店", "82", "1 天后发同小区收纳案例", "明天 10:00"],
  ["陈先生", "刚拿房 / 未设计", "已发户型图", "76", "2 天后发户型布局知识海报", "8/01 14:00"],
  ["周女士", "预算犹豫期", "问价后断联", "68", "今日发“包含项/可选项”报价解释", "今天 16:30"],
  ["吴先生", "暂缓装修", "已量房未签约", "61", "每 3 天一条环保与施工知识", "8/02 11:00"],
  ["张女士", "设计方案比较中", "看案例后断联", "74", "发奶油风选择题，补齐偏好", "明天 15:00"],
  ["黄先生", "刚拿房 / 未设计", "仅加企微", "52", "先发新房收纳清单，隔几天再联系", "8/03 10:30"],
  ["王女士", "预算犹豫期", "多次压价", "47", "暂不发活动，先发预算拆分知识", "8/02 17:00"],
  ["李先生", "已选别家", "明确拒绝", "22", "停止自动发送，保留人工备注", "已停止"],
];

export const conversations = [
  ["林女士", "92", "预算明确 · 周末有空", "14:42", "待店长检查"],
  ["陈先生", "88", "报价异议 · 已发户型", "14:28", "待店长检查"],
  ["周女士", "83", "环保板材 · 有小孩", "13:56", "没有明显问题"],
  ["吴先生", "79", "活动名额追问", "13:31", "需要留意"],
  ["张女士", "72", "地址偏远 · 想量房", "12:48", "待店长检查"],
  ["黄先生", "66", "多次压价", "11:52", "回复可能有错误"],
];
