export type ModuleKey = "video" | "sales" | "recall";

export type Screen = {
  id: string;
  module: ModuleKey;
  index: string;
  title: string;
  phase: string;
  summary: string;
  output: string;
  duration: string;
  instructions: string[];
  done: string[];
  detail?: boolean;
  parent?: string;
};

export const moduleMeta: Record<
  ModuleKey,
  { index: string; label: string; caption: string }
> = {
  video: { index: "01", label: "视频增长", caption: "8 个主页面" },
  sales: { index: "02", label: "企微销售", caption: "9 个主页面" },
  recall: { index: "03", label: "断联召回", caption: "8 个主页面" },
};

export const mainScreens: Screen[] = [
  {
    id: "video-business",
    module: "video",
    index: "01",
    title: "选择细分业务",
    phase: "引导流程",
    summary: "建立准确的业务画像，只为门店匹配真正相关的装修内容。",
    output: "业务画像",
    duration: "3 分钟",
    instructions: ["多选主营品类", "多选可服务区域", "保存业务信息", "在本页管理已保存内容"],
    done: ["主营品类已保存", "服务区域已保存", "可随时增删改"],
  },
  {
    id: "video-label",
    module: "video",
    index: "02",
    title: "匹配视频标注",
    phase: "引导流程",
    summary: "逐条判断 10 个样本是否匹配业务，校准系统对内容的理解。",
    output: "内容偏好",
    duration: "6 分钟",
    instructions: ["观看每条样本", "选择匹配或不匹配", "可修改已标记结果", "需要时继续标记更多"],
    done: ["10 条样本均已标记", "无遗漏结果", "偏好总结已更新"],
  },
  {
    id: "video-slices",
    module: "video",
    index: "03",
    title: "真实素材切片",
    phase: "引导流程",
    summary: "上传门店真实装修视频，自动识别可归档片段及其内容。",
    output: "素材片段库",
    duration: "5–15 分钟",
    instructions: ["上传本地视频", "等待分析完成", "检查片段描述", "进入详情编辑介绍"],
    done: ["视频分析完成", "片段可归档", "介绍内容已确认"],
  },
  {
    id: "video-spokesperson",
    module: "video",
    index: "04",
    title: "门店代言人素材",
    phase: "引导流程",
    summary: "建立主播或店长的可复用数字形象素材，规范照片和多种视频规格。",
    output: "代言人素材包",
    duration: "12 分钟",
    instructions: ["选择代言人角色", "上传正面照片", "上传三种口播视频", "检查光线、收音和动作"],
    done: ["照片符合规范", "三种视频已完成", "授权信息已确认"],
  },
  {
    id: "video-top",
    module: "video",
    index: "05",
    title: "竞品爆款 TOP10",
    phase: "每日任务",
    summary: "查看最近三天表现最好的 10 条竞品视频，并选择当天参考样本。",
    output: "参考视频",
    duration: "10 分钟",
    instructions: ["选择最近三天日期", "逐条观看大图预览", "比较点赞评论等参数", "选中一条参考视频"],
    done: ["10 条视频已浏览", "参数已比较", "今日参考视频已选"],
  },
  {
    id: "video-report",
    module: "video",
    index: "06",
    title: "爆款结构拆解",
    phase: "每日任务",
    summary: "拆解片段、转场、话术和主角特征，解释视频获得自然流量的原因。",
    output: "拆解报告",
    duration: "2–5 分钟",
    instructions: ["等待系统分析", "阅读自然量结论", "检查分镜和转场", "确认可复用结构"],
    done: ["结构报告生成", "话术与转场完整", "风险点已标注"],
  },
  {
    id: "video-progress",
    module: "video",
    index: "07",
    title: "视频制作进展",
    phase: "每日任务",
    summary: "从脚本、素材匹配、剪辑、字幕、配音到质检，实时查看每一步。",
    output: "制作日志",
    duration: "3–8 分钟",
    instructions: ["开始生成任务", "观察流水线进度", "定位异常原因", "仅重试失败步骤"],
    done: ["脚本与素材校验通过", "生成任务已开始", "日志无阻断错误"],
  },
  {
    id: "video-result",
    module: "video",
    index: "08",
    title: "成片与质检",
    phase: "每日任务",
    summary: "播放最终成片，检查清晰度、字幕、口播、品牌水印与内容风险。",
    output: "可发布成片",
    duration: "5 分钟",
    instructions: ["播放完整成片", "查看自动质检", "处理风险提示", "下载或重新生成"],
    done: ["所有质检通过", "成片可下载", "日任务完成"],
  },

  {
    id: "sales-training",
    module: "sales",
    index: "01",
    title: "销售培训资料",
    phase: "引导流程",
    summary: "上传销售手册、活动库、价格库和服务规范，建立机器人可信知识源。",
    output: "销售知识库",
    duration: "10 分钟",
    instructions: ["上传培训资料", "检查解析状态", "确认知识分类", "处理冲突条目"],
    done: ["核心资料已上传", "价格活动已入库", "冲突内容已处理"],
  },
  {
    id: "sales-champion",
    module: "sales",
    index: "02",
    title: "销冠对话样本",
    phase: "引导流程",
    summary: "提交 10 段真实销冠聊天，学习优秀顾问的提问、推进和收口方式。",
    output: "销冠策略样本",
    duration: "15 分钟",
    instructions: ["导入聊天记录", "匿名化客户信息", "标记关键轮次", "确认成功结果为到店"],
    done: ["10 段样本齐全", "关键策略已识别", "成功结果已确认"],
  },
  {
    id: "sales-simulation",
    module: "sales",
    index: "03",
    title: "模拟演练标注",
    phase: "引导流程",
    summary: "完成 100 个典型销售场景打分，帮助机器人理解业务判断标准。",
    output: "100 组标注",
    duration: "30–60 分钟",
    instructions: ["阅读客户问题", "查看机器人回答", "按四项标准打分", "修改不合格回答"],
    done: ["100 组均有评分", "低分回答已修改", "规则候选已生成"],
  },
  {
    id: "sales-prompt",
    module: "sales",
    index: "04",
    title: "风格与规则提示词",
    phase: "引导流程",
    summary: "查看并编辑机器人整体风格、承诺边界、推进目标和人工接管规则。",
    output: "机器人提示词",
    duration: "10 分钟",
    instructions: ["阅读自动总结", "编辑表达风格", "确认承诺边界", "发布新版本"],
    done: ["角色风格清楚", "价格与名额规则明确", "人工接管条件完整"],
  },
  {
    id: "sales-metrics",
    module: "sales",
    index: "05",
    title: "每日聊天数据",
    phase: "每日运营",
    summary: "监控新增会话、有效需求、到店预约、人工接管和机器人独立完成率。",
    output: "运营日报",
    duration: "5 分钟",
    instructions: ["选择日期", "查看核心漏斗", "比较前一日变化", "定位异常指标"],
    done: ["关键指标已查看", "异常已定位", "需要跟进的客户已进入列表"],
  },
  {
    id: "sales-quality",
    module: "sales",
    index: "06",
    title: "真实对话质检",
    phase: "每日运营",
    summary: "按成交意愿、时间和风险排序，逐个评价机器人真实对话。",
    output: "案例评价",
    duration: "15 分钟",
    instructions: ["优先查看高意向客户", "检查关键信息", "评价回答与推进策略", "必要时人工接管"],
    done: ["高意向案例已检查", "问题案例有明确标注", "接管任务已分配"],
  },
  {
    id: "sales-faq",
    module: "sales",
    index: "07",
    title: "高频问题优化",
    phase: "每日运营",
    summary: "优先修正问得最频繁的问题，统一回答内容、证据和转人工条件。",
    output: "高频问答库",
    duration: "15 分钟",
    instructions: ["按提问次数排序", "打开问题详情", "编辑标准答案", "发布并观察效果"],
    done: ["TOP10 问题已检查", "高频答案已优化", "引用依据可追溯"],
  },
  {
    id: "sales-plugins",
    module: "sales",
    index: "08",
    title: "对话插件中心",
    phase: "自动能力",
    summary: "统一查看户型方案、自动报价、免费量房与风格选择插件状态。",
    output: "插件组合",
    duration: "8 分钟",
    instructions: ["检查四个插件状态", "查看触发次数", "选择要配置的插件", "确认人工兜底"],
    done: ["必要插件已开通", "触发条件清楚", "人工兜底已设置"],
  },
  {
    id: "sales-plugin-config",
    module: "sales",
    index: "09",
    title: "插件开通与配置",
    phase: "自动能力",
    summary: "配置插件的触发条件、业务知识、自动动作和人工接管节点。",
    output: "可运行插件",
    duration: "12 分钟",
    instructions: ["选择插件", "填写触发条件", "绑定报价或服务库", "测试后开通"],
    done: ["触发条件通过测试", "可信数据已绑定", "插件已上线"],
  },

  {
    id: "recall-activities",
    module: "recall",
    index: "01",
    title: "活动与海报管理",
    phase: "每日运营",
    summary: "维护活动名称、周期、名额、权益和海报，供召回内容安全调用。",
    output: "活动内容库",
    duration: "10 分钟",
    instructions: ["新增或选择活动", "确认周期与名额", "上传海报", "保存并发布"],
    done: ["活动周期有效", "名额数据可用", "海报审核通过"],
  },
  {
    id: "recall-metrics",
    module: "recall",
    index: "02",
    title: "召回数据指标",
    phase: "每日运营",
    summary: "查看过去召回的送达、阅读、回复、预约量房与最终到店表现。",
    output: "召回分析",
    duration: "6 分钟",
    instructions: ["选择统计周期", "查看七次触达漏斗", "比较不同内容效果", "定位最佳触达"],
    done: ["核心指标已查看", "有效内容已识别", "异常触达已暂停"],
  },
  {
    id: "recall-pool",
    module: "recall",
    index: "03",
    title: "召回用户池",
    phase: "每日运营",
    summary: "按装修阶段、联系阶段、信任分和下一次触达时间管理召回客户。",
    output: "优先级名单",
    duration: "15 分钟",
    instructions: ["按成交意愿排序", "查看装修与联系阶段", "检查当前策略", "必要时转人工"],
    done: ["高意向客户已检查", "异常策略已调整", "人工任务已分配"],
  },
  {
    id: "recall-cadence",
    module: "recall",
    index: "04",
    title: "七次触达节奏",
    phase: "每日运营",
    summary: "逐次查看知识、案例、权益与关怀内容，调整间隔和停止条件。",
    output: "七次触达计划",
    duration: "12 分钟",
    instructions: ["选择客户分层", "检查七次内容", "调整触达间隔", "提交人工审核"],
    done: ["七次内容完整", "节奏符合阶段", "停止规则已设置"],
  },
  {
    id: "recall-plugins",
    module: "recall",
    index: "05",
    title: "召回插件中心",
    phase: "自动能力",
    summary: "管理个性化知识海报和免费上门测量券两类召回插件。",
    output: "召回插件组合",
    duration: "5 分钟",
    instructions: ["查看插件效果", "选择适用阶段", "检查触发规则", "进入内容配置"],
    done: ["插件已启用", "阶段规则明确", "数据来源可信"],
  },
  {
    id: "recall-poster",
    module: "recall",
    index: "06",
    title: "个性化知识海报",
    phase: "自动能力",
    summary: "根据客户阶段自动生成预算、板材、收纳与流程类知识海报。",
    output: "知识海报模板",
    duration: "8 分钟",
    instructions: ["选择客户阶段", "选择知识主题", "预览个性化内容", "保存模板"],
    done: ["文案与阶段匹配", "品牌信息正确", "无价格承诺风险"],
  },
  {
    id: "recall-coupon",
    module: "recall",
    index: "07",
    title: "免费上门测量券",
    phase: "自动能力",
    summary: "生成可核销的免费上门测量体验券，绑定服务区域、有效期和库存。",
    output: "体验券模板",
    duration: "8 分钟",
    instructions: ["设置适用区域", "设置有效期", "绑定预约库存", "预览并保存"],
    done: ["服务区域可覆盖", "有效期清楚", "库存同步正常"],
  },
  {
    id: "recall-review",
    module: "recall",
    index: "08",
    title: "发送审核与停止规则",
    phase: "每日运营",
    summary: "审核待发送内容，检查服务范围、活动库存、承诺边界与停止条件。",
    output: "安全发送队列",
    duration: "15 分钟",
    instructions: ["查看待发送内容", "检查业务数据证据", "批准、修改或停止", "记录审核结论"],
    done: ["高风险内容已处理", "发送依据完整", "停止规则已生效"],
  },
];

export const detailScreens: Screen[] = [
  ["video-label-detail", "video", "D01", "视频标注详情", "video-label", "完整观看样本并修改匹配判断"],
  ["video-slice-detail", "video", "D02", "素材切片详情", "video-slices", "查看每个拆分片段并编辑文字介绍"],
  ["video-spokesperson-detail", "video", "D03", "门店代言人详情", "video-spokesperson", "检查照片、口播规格与授权状态"],
  ["video-competitor-detail", "video", "D04", "竞品视频详情", "video-top", "查看完整视频、参数和评论洞察"],
  ["video-log-detail", "video", "D05", "生成任务日志详情", "video-progress", "追踪每一步输入、输出和异常重试"],
  ["video-result-detail", "video", "D06", "成片详情", "video-result", "查看版本、质检证据和下载记录"],
  ["sales-training-detail", "sales", "D07", "培训资料解析详情", "sales-training", "检查解析条目、冲突与可信来源"],
  ["sales-champion-detail", "sales", "D08", "销冠对话详情", "sales-champion", "逐轮拆解销冠提问、证明与邀约策略"],
  ["sales-simulation-detail", "sales", "D09", "模拟演练场景详情", "sales-simulation", "查看评分理由并改写机器人回答"],
  ["sales-conversation-detail", "sales", "D10", "真实对话案例详情", "sales-quality", "逐轮查看客户意图、机器人策略与接管时机"],
  ["sales-faq-detail", "sales", "D11", "高频问题详情", "sales-faq", "编辑标准回答、引用证据和适用边界"],
  ["recall-activity-detail", "recall", "D12", "活动详情", "recall-activities", "查看活动周期、库存、权益与发送记录"],
  ["recall-customer-detail", "recall", "D13", "客户召回详情", "recall-pool", "查看客户画像、信任分和完整召回历史"],
  ["recall-cadence-detail", "recall", "D14", "七次触达计划详情", "recall-cadence", "逐次编辑触达内容、间隔与停止条件"],
  ["recall-review-detail", "recall", "D15", "待发送审核详情", "recall-review", "核对业务证据后批准、修改或停止发送"],
].map(([id, module, index, title, parent, summary]) => ({
  id,
  module: module as ModuleKey,
  index,
  title,
  parent,
  phase: "详情页",
  summary,
  output: "详细记录",
  duration: "3–8 分钟",
  instructions: ["查看完整上下文", "检查系统依据", "编辑或确认结果", "返回主列表"],
  done: ["上下文已检查", "结果已保存", "操作记录完整"],
  detail: true,
}));

export const allScreens = [...mainScreens, ...detailScreens];

export const videos = [
  { title: "33㎡钻石厨房：台面多出 1.8 米", account: "漳州住小帮", duration: "00:42", views: "8.6万", likes: "6,842", comments: "312", saves: "1,486", shares: "729" },
  { title: "118㎡原木风全屋定制完工实拍", account: "有大有小全屋定制", duration: "00:36", views: "7.9万", likes: "5,901", comments: "286", saves: "1,224", shares: "614" },
  { title: "568 元/㎡套餐到底包含什么", account: "漳州定制阿杜", duration: "00:51", views: "6.8万", likes: "5,421", comments: "438", saves: "1,063", shares: "508" },
  { title: "8㎡儿童房收纳翻倍方案", account: "小户型改造局", duration: "00:29", views: "6.4万", likes: "4,872", comments: "197", saves: "1,522", shares: "469" },
  { title: "ENF 板材怎么选：三个误区", account: "板材研究社", duration: "00:47", views: "5.9万", likes: "4,215", comments: "369", saves: "1,305", shares: "392" },
  { title: "安装现场：柜门缝隙做到 2mm", account: "安装师傅老陈", duration: "00:33", views: "5.4万", likes: "3,986", comments: "241", saves: "892", shares: "361" },
  { title: "奶油风翻车的 5 个细节", account: "设计师周周", duration: "00:55", views: "4.9万", likes: "3,744", comments: "412", saves: "1,109", shares: "347" },
  { title: "旧房翻新先做柜体还是水电", account: "闽南旧改", duration: "00:40", views: "4.6万", likes: "3,205", comments: "334", saves: "948", shares: "298" },
  { title: "同户型改造前后动线对比", account: "空间答案", duration: "00:31", views: "4.2万", likes: "3,012", comments: "173", saves: "862", shares: "281" },
  { title: "店长带看：漳州龙文展厅", account: "有大有小门店", duration: "00:38", views: "3.8万", likes: "2,841", comments: "216", saves: "731", shares: "253" },
];

export const customers = [
  ["林女士", "设计方案比较中", "已报价未到店", "82", "1 天后发同小区收纳案例", "明天 10:00"],
  ["陈先生", "刚拿房 / 未设计", "已发户型图", "76", "2 天后发户型布局知识海报", "8/01 14:00"],
  ["周女士", "预算犹豫期", "问价后断联", "68", "今日发“包含项/可选项”报价解释", "今天 16:30"],
  ["吴先生", "暂缓装修", "已量房未签约", "61", "每 3 天一条环保与施工知识", "8/02 11:00"],
  ["张女士", "设计方案比较中", "看案例后断联", "74", "发奶油风选择题，补齐偏好", "明天 15:00"],
  ["黄先生", "刚拿房 / 未设计", "仅加企微", "52", "先发新房收纳清单，低频触达", "8/03 10:30"],
  ["王女士", "预算犹豫期", "多次压价", "47", "暂不发活动，先发预算拆分知识", "8/02 17:00"],
  ["李先生", "已选竞品", "明确拒绝", "22", "停止自动发送，保留人工备注", "已停止"],
];

export const conversations = [
  ["林女士", "92", "预算明确 · 周末有空", "14:42", "待质检"],
  ["陈先生", "88", "报价异议 · 已发户型", "14:28", "待质检"],
  ["周女士", "83", "环保板材 · 有小孩", "13:56", "低风险"],
  ["吴先生", "79", "活动名额追问", "13:31", "需关注"],
  ["张女士", "72", "地址偏远 · 想量房", "12:48", "待质检"],
  ["黄先生", "66", "多次压价", "11:52", "高风险"],
];
